CREATE DATABASE QLNganHang
USE QLNganHang

CREATE TABLE KHACHHANG
(
	USERNAME VARCHAR(40) PRIMARY KEY,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	EMAIL VARCHAR(40),
	PASSWORD VARCHAR(40),
	GIOTINH CHAR(1),
	STK VARCHAR(10),
	BANK VARCHAR(40),
	TIEN INT,
	STKdefault VARCHAR(1),
	TIMECREATE DATETIME,
	SAVING VARCHAR(1),
	INTEREST FLOAT
)

CREATE TABLE HOADON (
    MaGiaoDich INT PRIMARY KEY,
    SoTaiKhoanChuyen VARCHAR(20),
    SoTienChuyen INT,
    TenNguoiThuHuong NVARCHAR(255),
    TaiKhoanThuHuong VARCHAR(20),
    NganHangThuHuong NVARCHAR(100),
    NoiDungChuyenTien NVARCHAR(100),
	ThoiGianGD	DateTIME,
	username VARCHAR(40),
	totalMoneyFrom INT,
	totalMoneyTo INT,
	seen VARCHAR(1)
);

CREATE TABLE HOADON_filtered (
    MaGiaoDich INT PRIMARY KEY,
    SoTaiKhoanChuyen VARCHAR(20),
    SoTienChuyen INT,
    TenNguoiThuHuong NVARCHAR(255),
    TaiKhoanThuHuong VARCHAR(20),
    NganHangThuHuong NVARCHAR(100),
    NoiDungChuyenTien NVARCHAR(100),
	ThoiGianGD	DateTIME,
	username NVARCHAR(100),
	totalMoneyFrom INT,
	totalMoneyTo INT,
	seen VARCHAR(1)
);

CREATE TABLE ONLINE (
	USERNAME VARCHAR(40),
	NAME VARCHAR(40),
	STK VARCHAR(10),
	BANK VARCHAR(40),
	TIMEIN DATETIME,
	REMEMBER VARCHAR(1),
	PASSWORD VARCHAR(40)
)

ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH
FOREIGN KEY (USERNAME) REFERENCES KHACHHANG(USERNAME)
