CREATE TABLE KHACHHANG
(
	USERNAME VARCHAR(40),
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	EMAIL VARCHAR(40),
	PASSWORD VARCHAR(40),
	GIOTINH CHAR(1),
	STK VARCHAR(10),
	BANK VARCHAR(40),
	TIEN INT,
	STKdefault VARCHAR(1),
	TIMECREATE DATETIME,
	SAVING VARCHAR(1),
	INTEREST FLOAT
)

DROP TABLE KHACHHANG

SELECT * FROM KHACHHANG

SELECT TIEN FROM KHACHHANG WHERE STK='8933112207'

SELECT * FROM ONLINE

SELECT * FROM ONLINE

ALTER TABLE HOADON ADD CONSTRAINT FK_HD_KH
FOREIGN KEY (USERNAME) REFERENCES KHACHHANG(USERNAME)

SELECT * FROM KHACHHANG
DROP TABLE KHACHHANG

INSERT INTO KHACHHANG VALUES('havold','TRƯƠNG HUU THO','0833873869','3/7/2003','huutho030703@gmail.com','982982','M','1234567890','BIDV',2000000,'F','2023-12-23 08:52:48.000','F',0)

INSERT INTO KHACHHANG VALUES('havold','TRUONG HUU THO','N','2023-12-23','N','N','N','123123123','BIDV',12000,'N','2023-12-23')

CREATE TABLE HOADON (
    MaGiaoDich INT PRIMARY KEY,
    SoTaiKhoanChuyen VARCHAR(20),
    SoTienChuyen INT,
    TenNguoiThuHuong NVARCHAR(255),
    TaiKhoanThuHuong VARCHAR(20),
    NganHangThuHuong NVARCHAR(100),
    NoiDungChuyenTien NVARCHAR(100),
	ThoiGianGD	DateTIME,
	username NVARCHAR(100),
	totalMoneyFrom INT,
	totalMoneyTo INT,
	seen VARCHAR(1)
);

CREATE TABLE HOADON_filtered (
    MaGiaoDich INT PRIMARY KEY,
    SoTaiKhoanChuyen VARCHAR(20),
    SoTienChuyen INT,
    TenNguoiThuHuong NVARCHAR(255),
    TaiKhoanThuHuong VARCHAR(20),
    NganHangThuHuong NVARCHAR(100),
    NoiDungChuyenTien NVARCHAR(100),
	ThoiGianGD	DateTIME,
	username NVARCHAR(100),
	totalMoneyFrom INT,
	totalMoneyTo INT,
	seen VARCHAR(1)
);


SELECT * FROM HOADON
DROP TABLE HOADON


CREATE TABLE ONLINE (
	USERNAME VARCHAR(40),
	NAME VARCHAR(40),
	STK VARCHAR(10),
	BANK VARCHAR(40),
	TIMEIN DATETIME,
	REMEMBER VARCHAR(1),
	PASSWORD VARCHAR(40)
)

SELECT * FROM ONLINE

DROP TABLE ONLINE

SELECT * FROM KHACHHANG
SELECT * FROM HOADON



SELECT *
FROM HOADON
WHERE HOADON.

SELECT TOP 1 username
FROM ONLINE

SELECT *
FROM HOADON 
WHERE HOADON.SoTaiKhoanChuyen= (SELECT TOP 1 username
FROM ONLINE)

-- IN C#

SELECT HOADON.* FROM KHACHHANG INNER JOIN HOADON ON KHACHHANG.STK = HOADON.SoTaiKhoanChuyen WHERE KHACHHANG.USERNAME = 'havold' ORDER BY HOADON.ThoiGianGD DESC

UPDATE HOADON SET seen = 'S' FROM KHACHHANG INNER JOIN HOADON ON KHACHHANG.STK = HOADON.SoTaiKhoanChuyen WHERE KHACHHANG.USERNAME = 'your_username' AND HOADON.seen = 'N' 


SELECT TOP 1 * FROM ONLINE ORDER BY TIMEIN DESC; -- Sắp xếp giảm dần theo trường thời gian


SELECT HOADON.* FROM KHACHHANG INNER JOIN HOADON ON KHACHHANG.STK = HOADON.SoTaiKhoanChuyen OR KHACHHANG.STK= HOADON.TaiKhoanThuHuong WHERE KHACHHANG.STK = '1234567890' ORDER BY HOADON.ThoiGianGD DESC



-- LỌC THÔNG TIN HÓA ĐƠN TỪ NGÀY START ĐẾN END
INSERT INTO HOADON_Filtered
SELECT *
FROM HOADON
WHERE ThoiGianGD BETWEEN '2023-12-01' AND '2023-12-23'

-- C#
INSERT INTO HOADON_Filtered SELECT * FROM HOADON WHERE ThoiGianGD BETWEEN '2023-12-01' AND '2023-12-23'


SELECT * FROM HOADON_filtered
DELETE FROM HOADON_Filtered

SELECT HOADON_Filtered.* FROM KHACHHANG INNER JOIN HOADON_Filtered ON KHACHHANG.STK = HOADON_Filtered.SoTaiKhoanChuyen OR KHACHHANG.STK= HOADON_Filtered.TaiKhoanThuHuong WHERE KHACHHANG.STK = '1234567890' 

SELECT HOADON_Filtered.* FROM KHACHHANG INNER JOIN HOADON_Filtered ON KHACHHANG.STK = HOADON_Filtered.SoTaiKhoanChuyen OR KHACHHANG.STK= HOADON_Filtered.TaiKhoanThuHuong WHERE KHACHHANG.STK = '8933112207' ORDER BY ThoiGianGD DESC


INSERT INTO HOADON_Filtered SELECT * FROM HOADON WHERE ThoiGianGD BETWEEN '2023-12-22' AND '2023-12-23'
SELECT * FROM HOADON 

SELECT STK,TIEN,TIMECREATE FROM KHACHHANG WHERE KHACHHANG.USERNAME = 'havold' ORDER BY TIMECREATE DESC

SELECT TOP 1 USERNAME,STK,BANK FROM ONLINE ORDER BY TIMEIN DESC

-- UPDATE ONLINE SAU KHI CẬP NHẬT DEFAULT
UPDATE ONLINE
SET STK = '12345'
WHERE STK = (
    SELECT TOP 1 STK
    FROM ONLINE
    ORDER BY TIMEIN DESC
);

UPDATE ONLINE SET STK = '12345' WHERE STK = ( SELECT TOP 1 STK FROM ONLINE ORDER BY TIMEIN DESC)

SELECT TOP 1 MAGIAODICH,SOTIENCHUYEN,TAIKHOANTHUHUONG,TENNGUOITHUHUONG,NGANHANGTHUHUONG,NOIDUNGCHUYENTIEN,THOIGIANGD FROM KHACHHANG INNER JOIN HOADON ON KHACHHANG.STK = HOADON.SoTaiKhoanChuyen OR KHACHHANG.STK= HOADON.TaiKhoanThuHuong ORDER BY HOADON.ThoiGianGD DESC

SELECT TOP 1 SODT,NGSINH, EMAIL,GIOITINH FROM KHACHHANG WHERE KHACHHANG.USERNAME='havold' AND KHACHHANG.HOTEN='TRUONG HUU THO'